version: "3.9"

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  client-a-data:
  client-b-data:

services:

  # ---------------- TRAEFIK ----------------
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=app-network
      - --entrypoints.web.address=:80

  # ---------------- CLIENT A ----------------
  client-a:
    image: rushid03/client-a:${IMAGE_TAG}
    networks:
      - app-network
    volumes:
      - client-a-data:/data
    secrets:
      - client_a_db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client-a.rule=PathPrefix(`/client-a`)"
        - "traefik.http.routers.client-a.entrypoints=web"
        - "traefik.http.services.client-a.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.client-a-strip.stripprefix.prefixes=/client-a"
        - "traefik.http.routers.client-a.middlewares=client-a-strip"

  # ---------------- CLIENT B ----------------
  client-b:
    image: rushid03/client-b:${IMAGE_TAG}
    networks:
      - app-network
    volumes:
      - client-b-data:/data
    secrets:
      - client_b_db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client-b.rule=PathPrefix(`/client-b`)"
        - "traefik.http.routers.client-b.entrypoints=web"
        - "traefik.http.services.client-b.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.client-b-strip.stripprefix.prefixes=/client-b"
        - "traefik.http.routers.client-b.middlewares=client-b-strip"

secrets:
  client_a_db:
    external: true
  client_b_db:
    external: true
